### ISSUE TITLE
isScanned cannot find isBioOne

### ISSUE THREAD

**Issue by mespe** [dsidavis/ReadPDF#1]

**Comment by duncantl** [comment]
Thanks. Yep, I know. It is in the Zoonotics-shared.
We need to generalize the function to take a filter function.
I'll get to it.
Do you need it ASAP?

**Comment by mespe** [comment]
Don't need it right away - the interns were playing around with it.

**Comment by duncantl** [comment]
Pushed the change. 
You can now specify a function or a list of functions to isScanned() in the second parameter.
These functions are called with the document and can determine whether they have particular characteristics that indicate scanned or not, e.g. BioOne on the first page.

**Comment by duncantl** [comment]
Hopefully we can close this one?

**Comment by mespe** [comment]
Yes - sorry, I thought it got closed already.
